### ISSUE TITLE
More flavors

### ISSUE THREAD

**Issue by nasiralamreeki** [JAKAMI99/wpa-sec-docker-nvidia#4]
Can you make a generic docker for regular CPU? I can drop this on a bunch of cloud servers I have

**Comment by JAKAMI99** [comment]
hi!
Thanks for the interest, but I can't recommend cracking on CPU.
A CPU is a build as a general-purpose piece of hardware, a GPU on the other hand is designed to handle a few tasks very efficiently and fast.
This way, cracking is far more efficient and quicker on GPU, and usually it should be avoided to crack on CPU.

On what kind of system do you want to install this docker? Maybe a different approach would help you, or it might be interesting to you to invest into a cheap GPU like a 1050ti which does the cracking job perfectly

**Comment by JAKAMI99** [comment]
I am happy to help you, but will close this issue for now. 
Feel free to still answer to this issue and if needed we can reopen it
